{{- $name := include "database-controller.name" . -}}
{{- $version := include "database-controller.version" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    version: {{ $version }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
  {{- with .Values.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        version: {{ $version }}
        {{- with .Values.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- with .Values.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ $name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-leader
              containerPort: 9443
              protocol: TCP
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          command: ["/manager"]
          args:
            - "--enable-leader-election"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
