apiVersion: database.stacc.com/v1alpha1
kind: DatabaseServer
metadata:
  name: mongo-server
spec:
  type: mongo
  mongo:
    host: localhost
    username: admin
    port: 27017
    ssl: false
  secret:
    name: mongo-server-secret
    namespace: default