apiVersion: database.stacc.com/v1alpha1
kind: Database
metadata:
  name: postgres-db
spec:
  name: postgres-db
  username: postgres-user
  reclaimPolicy: delete
  server:
    name: postgres-server
    namespace: default
  secret:
    name: postgres-db-secret
    namespace: default