apiVersion: database.stacc.com/v1alpha1
kind: DatabaseServer
metadata:
  name: postgres-server
spec:
  type: postgres
  postgres:
    host: localhost
    username: postgres
    port: 5432
    sslmode: require
  secret:
    name: postgres-server-secret
    namespace: default