apiVersion: database.stacc.com/v1alpha1
kind: Database
metadata:
  name: mysql-db
  finalizers:
    - database.stacc.com/finalizer
spec:
  server:
    name: mysql-server
    namespace: default
  name: mysqldb
  secret:
    name: mysql-db-secret
    namespace: default
  deletable: true