apiVersion: database.stacc.com/v1alpha1
kind: Database
metadata:
  name: mysql-db
spec:
  name: mysqldb
  reclaimPolicy: delete
  server:
    name: mysql-server
    namespace: default
  secret:
    name: mysql-db-secret
    namespace: default