apiVersion: database.stacc.com/v1alpha1
kind: DatabaseServer
metadata:
  name: mysql-server
spec:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    username: my
    ssl: false
  secret:
    name: mysql-server-secret
    namespace: default