apiVersion: database.stacc.com/v1alpha1
kind: DatabaseServer
metadata:
  name: postgres-server
spec:
  type: postgresql
  secretName: postgres-server-secret
  postgres:
    host: localhost
    username: postgres
    port: 5432
    useSsl: false
