{{- $name := include "database-controller.name" . -}}
{{- $version := include "database-controller.version" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    version: {{ $version }}
