image:
  repository: ghcr.io/austien/database-provisioning-controller-poc
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

nameOverride:

imagePullSecrets: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

additionalAnnotations: {}

additionalLabels: {}

istio:
  enabled: false

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

serviceMonitor:
  enabled: false
  additionalLabels: {}
